FROM tensorflow/tensorflow:1.15.5-gpu
COPY ./Miniconda3-py37_4.9.2-Linux-x86_64.sh /tmp/
COPY ./pip.conf /tmp
COPY ./requirements.txt /tmp
ENV PATH="/root/miniconda3/bin:${PATH}"
ARG PATH="/root/miniconda3/bin:${PATH}"

RUN mkdir /root/.conda \
    && bash /tmp/Miniconda3-py37_4.9.2-Linux-x86_64.sh -b \
    && cd /root/miniconda3/bin/ \
    && ./pip install -r /tmp/requirements.txt
